import { scale } from './scale';
import { StyleSheet } from 'react-native';
import commonColors from './colors';

export const defaultStyles = StyleSheet.create({
  //MARK: flex size
  flex1: {
    flex: 1,
  },
  flex2: {
    flex: 2,
  },
  flex3: {
    flex: 3,
  },
  flex4: {
    flex: 4,
  },
  flex5: {
    flex: 5,
  },
  flex6: {
    flex: 6,
  },
  flex7: {
    flex: 7,
  },
  flex8: {
    flex: 8,
  },
  flex9: {
    flex: 9,
  },
  flex10: {
    flex: 10,
  },

  //MARK: flex grow
  flexGrow1: {
    flexGrow: 1,
  },
  flexGrow2: {
    flexGrow: 2,
  },
  flexGrow3: {
    flexGrow: 3,
  },
  flexGrow4: {
    flexGrow: 4,
  },
  flexGrow5: {
    flexGrow: 5,
  },
  flexGrow6: {
    flexGrow: 6,
  },
  flexGrow7: {
    flexGrow: 7,
  },
  flexGrow8: {
    flexGrow: 8,
  },
  flexGrow9: {
    flexGrow: 9,
  },
  flexGrow10: {
    flexGrow: 10,
  },

  //MARK: flex direction
  flexDirectionRow: {
    flexDirection: 'row',
  },
  flexDirectionColumn: {
    flexDirection: 'column',
  },
  flexDirectionRowReverse: { flexDirection: 'row-reverse' },

  //MARK: flex wrap
  flexWrap: {
    flexWrap: 'wrap',
  },

  //MARK: position
  positionAbsolute: {
    position: 'absolute',
  },
  positionRelative: {
    position: 'relative',
  },

  //MARK: content and container alignment
  justifyCenter: {
    justifyContent: 'center',
  },
  alignCenter: {
    alignItems: 'center',
  },
  alignStart: {
    alignItems: 'flex-start',
  },
  alignSelfFlexEnd: {
    alignSelf: 'flex-end',
  },
  alignSelfFlexStart: {
    alignSelf: 'flex-start',
  },
  alignSelfCenter: {
    alignSelf: 'center',
  },
  contentCenter: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  alignContentCenter: {
    alignContent: 'center',
  },
  alignItemsEnd: {
    alignItems: 'flex-end',
  },
  alignItemsCenter: {
    alignItems: 'center',
  },
  alignItemsStart: {
    alignItems: 'flex-start',
  },
  justifySpaceBetween: {
    justifyContent: 'space-between',
  },
  justifySpaceEvenly: {
    justifyContent: 'space-evenly',
  },
  justifyFlexStart: {
    justifyContent: 'flex-start',
  },
  justifyFlexEnd: {
    justifyContent: 'flex-end',
  },
  justifyContentCenter: {
    justifyContent: 'center',
  },

  //MARK: over flow
  overflowHidden: {
    overflow: 'hidden',
  },
  overflowScroll: {
    overflow: 'scroll',
  },

  //MARK: text alignments
  textAlignCenter: {
    textAlign: 'center',
  },
  textAlignLeft: {
    textAlign: 'left',
  },
  textAlignRight: {
    textAlign: 'right',
  },

  //MARK: text styles
  underLineText: {
    textDecorationLine: 'underline',
  },

  //MARK: text line height
  lineHeight1: { lineHeight: scale(1) },
  lineHeight2: { lineHeight: scale(2) },
  lineHeight3: { lineHeight: scale(3) },
  lineHeight4: { lineHeight: scale(4) },
  lineHeight5: { lineHeight: scale(5) },
  lineHeight6: { lineHeight: scale(6) },
  lineHeight7: { lineHeight: scale(7) },
  lineHeight8: { lineHeight: scale(8) },
  lineHeight9: { lineHeight: scale(9) },
  lineHeight10: { lineHeight: scale(10) },
  lineHeight11: { lineHeight: scale(11) },
  lineHeight12: { lineHeight: scale(12) },
  lineHeight13: { lineHeight: scale(13) },
  lineHeight14: { lineHeight: scale(14) },
  lineHeight15: { lineHeight: scale(15) },
  lineHeight16: { lineHeight: scale(16) },
  lineHeight17: { lineHeight: scale(17) },
  lineHeight18: { lineHeight: scale(18) },
  lineHeight19: { lineHeight: scale(19) },
  lineHeight20: { lineHeight: scale(20) },
  lineHeight21: { lineHeight: scale(21) },
  lineHeight22: { lineHeight: scale(22) },
  lineHeight23: { lineHeight: scale(23) },
  lineHeight24: { lineHeight: scale(24) },
  lineHeight25: { lineHeight: scale(25) },
  lineHeight26: { lineHeight: scale(26) },
  lineHeight27: { lineHeight: scale(27) },
  lineHeight28: { lineHeight: scale(28) },
  lineHeight29: { lineHeight: scale(29) },
  lineHeight30: { lineHeight: scale(30) },
  lineHeight31: { lineHeight: scale(31) },
  lineHeight32: { lineHeight: scale(32) },
  lineHeight33: { lineHeight: scale(33) },
  lineHeight34: { lineHeight: scale(34) },
  lineHeight35: { lineHeight: scale(35) },
  lineHeight36: { lineHeight: scale(36) },
  lineHeight37: { lineHeight: scale(37) },
  lineHeight38: { lineHeight: scale(38) },
  lineHeight39: { lineHeight: scale(39) },
  lineHeight40: { lineHeight: scale(40) },
  lineHeight41: { lineHeight: scale(41) },
  lineHeight42: { lineHeight: scale(42) },
  lineHeight43: { lineHeight: scale(43) },
  lineHeight44: { lineHeight: scale(44) },
  lineHeight45: { lineHeight: scale(45) },
  lineHeight46: { lineHeight: scale(46) },
  lineHeight47: { lineHeight: scale(47) },
  lineHeight48: { lineHeight: scale(48) },
  lineHeight49: { lineHeight: scale(49) },
  lineHeight50: { lineHeight: scale(50) },
  lineHeight51: { lineHeight: scale(51) },
  lineHeight52: { lineHeight: scale(52) },
  lineHeight53: { lineHeight: scale(53) },
  lineHeight54: { lineHeight: scale(54) },
  lineHeight55: { lineHeight: scale(55) },
  lineHeight56: { lineHeight: scale(56) },
  lineHeight57: { lineHeight: scale(57) },
  lineHeight58: { lineHeight: scale(58) },
  lineHeight59: { lineHeight: scale(59) },
  lineHeight60: { lineHeight: scale(60) },
  lineHeight61: { lineHeight: scale(61) },
  lineHeight62: { lineHeight: scale(62) },
  lineHeight63: { lineHeight: scale(63) },
  lineHeight64: { lineHeight: scale(64) },
  lineHeight65: { lineHeight: scale(65) },
  lineHeight66: { lineHeight: scale(66) },
  lineHeight67: { lineHeight: scale(67) },
  lineHeight68: { lineHeight: scale(68) },
  lineHeight69: { lineHeight: scale(69) },
  lineHeight70: { lineHeight: scale(70) },
  lineHeight71: { lineHeight: scale(71) },
  lineHeight72: { lineHeight: scale(72) },
  lineHeight73: { lineHeight: scale(73) },
  lineHeight74: { lineHeight: scale(74) },
  lineHeight75: { lineHeight: scale(75) },
  lineHeight76: { lineHeight: scale(76) },
  lineHeight77: { lineHeight: scale(77) },
  lineHeight78: { lineHeight: scale(78) },
  lineHeight79: { lineHeight: scale(79) },
  lineHeight80: { lineHeight: scale(80) },
  lineHeight81: { lineHeight: scale(81) },
  lineHeight82: { lineHeight: scale(82) },
  lineHeight83: { lineHeight: scale(83) },
  lineHeight84: { lineHeight: scale(84) },
  lineHeight85: { lineHeight: scale(85) },
  lineHeight86: { lineHeight: scale(86) },
  lineHeight87: { lineHeight: scale(87) },
  lineHeight88: { lineHeight: scale(88) },
  lineHeight89: { lineHeight: scale(89) },
  lineHeight90: { lineHeight: scale(90) },
  lineHeight91: { lineHeight: scale(91) },
  lineHeight92: { lineHeight: scale(92) },
  lineHeight93: { lineHeight: scale(93) },
  lineHeight94: { lineHeight: scale(94) },
  lineHeight95: { lineHeight: scale(95) },
  lineHeight96: { lineHeight: scale(96) },
  lineHeight97: { lineHeight: scale(97) },
  lineHeight98: { lineHeight: scale(98) },
  lineHeight99: { lineHeight: scale(99) },
  lineHeight100: { lineHeight: scale(100) },

  //MARK:  font types
  Circe_Bold: {
    fontFamily: 'CirceBold-Bold',
  },
  Circe_Regular: {
    fontFamily: 'Circe-Regular',
  },

  //MARK: font styles
  fontWeightBold: {
    fontWeight: 'bold',
  },

  letterSpacing2: {
    letterSpacing: 0.2,
  },

  //MARK:  font sizes
  fontSize10: { fontSize: scale(10) },
  fontSize11: { fontSize: scale(11) },
  fontSize12: { fontSize: scale(12) },
  fontSize13: { fontSize: scale(13) },
  fontSize14: { fontSize: scale(14) },
  fontSize15: { fontSize: scale(15) },
  fontSize16: { fontSize: scale(16) },
  fontSize17: { fontSize: scale(17) },
  fontSize18: { fontSize: scale(18) },
  fontSize19: { fontSize: scale(19) },
  fontSize20: { fontSize: scale(20) },
  fontSize21: { fontSize: scale(21) },
  fontSize22: { fontSize: scale(22) },
  fontSize23: { fontSize: scale(23) },
  fontSize24: { fontSize: scale(24) },
  fontSize25: { fontSize: scale(25) },
  fontSize26: { fontSize: scale(26) },
  fontSize27: { fontSize: scale(27) },
  fontSize28: { fontSize: scale(28) },
  fontSize29: { fontSize: scale(29) },
  fontSize30: { fontSize: scale(30) },
  fontSize31: { fontSize: scale(31) },
  fontSize32: { fontSize: scale(32) },
  fontSize33: { fontSize: scale(33) },
  fontSize34: { fontSize: scale(34) },
  fontSize35: { fontSize: scale(35) },
  fontSize36: { fontSize: scale(36) },
  fontSize37: { fontSize: scale(37) },
  fontSize38: { fontSize: scale(38) },
  fontSize39: { fontSize: scale(39) },
  fontSize40: { fontSize: scale(40) },
  fontSize41: { fontSize: scale(41) },
  fontSize42: { fontSize: scale(42) },
  fontSize43: { fontSize: scale(43) },
  fontSize44: { fontSize: scale(44) },
  fontSize45: { fontSize: scale(45) },
  fontSize46: { fontSize: scale(46) },
  fontSize47: { fontSize: scale(47) },
  fontSize48: { fontSize: scale(48) },
  fontSize49: { fontSize: scale(49) },
  fontSize50: { fontSize: scale(50) },
  fontSize51: { fontSize: scale(51) },
  fontSize52: { fontSize: scale(52) },
  fontSize53: { fontSize: scale(53) },
  fontSize54: { fontSize: scale(54) },
  fontSize55: { fontSize: scale(55) },
  fontSize56: { fontSize: scale(56) },
  fontSize57: { fontSize: scale(57) },
  fontSize58: { fontSize: scale(58) },
  fontSize59: { fontSize: scale(59) },
  fontSize60: { fontSize: scale(60) },
  fontSize61: { fontSize: scale(61) },
  fontSize62: { fontSize: scale(62) },
  fontSize63: { fontSize: scale(63) },
  fontSize64: { fontSize: scale(64) },
  fontSize65: { fontSize: scale(65) },
  fontSize66: { fontSize: scale(66) },
  fontSize67: { fontSize: scale(67) },
  fontSize68: { fontSize: scale(68) },
  fontSize69: { fontSize: scale(69) },
  fontSize70: { fontSize: scale(70) },
  fontSize71: { fontSize: scale(71) },
  fontSize72: { fontSize: scale(72) },
  fontSize73: { fontSize: scale(73) },
  fontSize74: { fontSize: scale(74) },
  fontSize75: { fontSize: scale(75) },
  fontSize76: { fontSize: scale(76) },
  fontSize77: { fontSize: scale(77) },
  fontSize78: { fontSize: scale(78) },
  fontSize79: { fontSize: scale(79) },
  fontSize80: { fontSize: scale(80) },
  fontSize81: { fontSize: scale(81) },
  fontSize82: { fontSize: scale(82) },
  fontSize83: { fontSize: scale(83) },
  fontSize84: { fontSize: scale(84) },
  fontSize85: { fontSize: scale(85) },
  fontSize86: { fontSize: scale(86) },
  fontSize87: { fontSize: scale(87) },
  fontSize88: { fontSize: scale(88) },
  fontSize89: { fontSize: scale(89) },
  fontSize90: { fontSize: scale(90) },
  fontSize91: { fontSize: scale(91) },
  fontSize92: { fontSize: scale(92) },
  fontSize93: { fontSize: scale(93) },
  fontSize94: { fontSize: scale(94) },
  fontSize95: { fontSize: scale(95) },
  fontSize96: { fontSize: scale(96) },
  fontSize97: { fontSize: scale(97) },
  fontSize98: { fontSize: scale(98) },
  fontSize99: { fontSize: scale(99) },
  fontSize100: { fontSize: scale(100) },

  //MARK: font colors
  colorWhite_FFFFFF: { color: commonColors.white_FFFFFF },
  colorBlack_000000: { color: commonColors.black_000000 },
  colorGray_808080: { color: commonColors.gray_808080 },
  colorRed_FF0000: { color: commonColors.red_FF0000 },
  colorBlue_0000FF: { color: commonColors.blue_0000FF },
  colorGreen_00FF00: { color: commonColors.green_00FF00 },
  colorYellow_FFFF00: { color: commonColors.yellow_FFFF00 },
  colorCyan_00FFFF: { color: commonColors.cyan_00FFFF },
  colorMagenta_FF00FF: { color: commonColors.magenta_FF00FF },
  colorOrange_FF9900: { color: commonColors.orange_FF9900 },
  colorPurple_800080: { color: commonColors.purple_800080 },
  colorBrown_A52A2A: { color: commonColors.brown_A52A2A },
  colorGold_FFCC00: { color: commonColors.gold_FFCC00 },
  colorSilver_C0C0C0: { color: commonColors.silver_C0C0C0 },
  colorNavy_000080: { color: commonColors.navy_000080 },
  colorOlive_808000: { color: commonColors.olive_808000 },
  colorTeal_008080: { color: commonColors.teal_008080 },
  colorPink_FF69B4: { color: commonColors.pink_FF69B4 },
  colorLavender_E6E6FA: { color: commonColors.lavender_E6E6FA },
  colorCoral_FF7F50: { color: commonColors.coral_FF7F50 },
  colorIndigo_4B0082: { color: commonColors.indigo_4B0082 },
  colorViolet_EE82EE: { color: commonColors.violet_EE82EE },
  colorPeach_FFDAB9: { color: commonColors.peach_FFDAB9 },
  colorMint_98FB98: { color: commonColors.mint_98FB98 },
  colorSalmon_FA8072: { color: commonColors.salmon_FA8072 },
  colorBeige_F5F5DC: { color: commonColors.beige_F5F5DC },
  colorKhaki_F0E68C: { color: commonColors.khaki_F0E68C },
  colorIvory_FFFFF0: { color: commonColors.ivory_FFFFF0 },
  colorSienna_A0522D: { color: commonColors.sienna_A0522D },
  colorAzure_F0FFFF: { color: commonColors.azure_F0FFFF },
  colorOrchid_DA70D6: { color: commonColors.orchid_DA70D6 },
  colorChocolate_D2691E: { color: commonColors.chocolate_D2691E },
  colorTomato_FF6347: { color: commonColors.tomato_FF6347 },
  colorAqua_00FFFF: { color: commonColors.aqua_00FFFF },
  colorSkyblue_87CEEB: { color: commonColors.skyblue_87CEEB },
  colorLinen_FAF0E6: { color: commonColors.linen_FAF0E6 },
  colorBisque_FFE4C4: { color: commonColors.bisque_FFE4C4 },
  colorHoneydew_F0FFF0: { color: commonColors.honeydew_F0FFF0 },
  colorLemonchiffon_FFFACD: { color: commonColors.lemonchiffon_FFFACD },
  colorMistyrose_FFE4E1: { color: commonColors.mistyrose_FFE4E1 },
  colorMoccasin_FFE4B5: { color: commonColors.moccasin_FFE4B5 },
  colorNavajowhite_FFDEAD: { color: commonColors.navajowhite_FFDEAD },
  colorOldlace_FDF5E6: { color: commonColors.oldlace_FDF5E6 },
  colorPapayawhip_FFEFD5: { color: commonColors.papayawhip_FFEFD5 },
  colorSeashell_FFF5EE: { color: commonColors.seashell_FFF5EE },
  colorSnow_FFFAFA: { color: commonColors.snow_FFFAFA },
  colorWhitesmoke_F5F5F5: { color: commonColors.whitesmoke_F5F5F5 },
  colorYellowgreen_9ACD32: { color: commonColors.yellowgreen_9ACD32 },
  colorAntiquewhite_FAEBD7: { color: commonColors.antiquewhite_FAEBD7 },
  colorCornflowerblue_6495ED: { color: commonColors.cornflowerblue_6495ED },
  colorDarkblue_00008B: { color: commonColors.darkblue_00008B },
  colorDarkcyan_008B8B: { color: commonColors.darkcyan_008B8B },
  colorDarkgoldenrod_B8860B: { color: commonColors.darkgoldenrod_B8860B },
  colorDarkgray_A9A9A9: { color: commonColors.darkgray_A9A9A9 },
  colorDarkgreen_006400: { color: commonColors.darkgreen_006400 },

  //MARK:  background Colors
  bgColorTransparent: { backgroundColor: commonColors.transparent },
  bgColorWhite_FFFFFF: { backgroundColor: commonColors.white_FFFFFF },
  bgColorBlack_000000: { backgroundColor: commonColors.black_000000 },
  bgColorGray_808080: { backgroundColor: commonColors.gray_808080 },
  bgColorRed_FF0000: { backgroundColor: commonColors.red_FF0000 },
  bgColorBlue_0000FF: { backgroundColor: commonColors.blue_0000FF },
  bgColorGreen_00FF00: { backgroundColor: commonColors.green_00FF00 },
  bgColorYellow_FFFF00: { backgroundColor: commonColors.yellow_FFFF00 },
  bgColorCyan_00FFFF: { backgroundColor: commonColors.cyan_00FFFF },
  bgColorMagenta_FF00FF: { backgroundColor: commonColors.magenta_FF00FF },
  bgColorOrange_FF9900: { backgroundColor: commonColors.orange_FF9900 },
  bgColorPurple_800080: { backgroundColor: commonColors.purple_800080 },
  bgColorBrown_A52A2A: { backgroundColor: commonColors.brown_A52A2A },
  bgColorGold_FFCC00: { backgroundColor: commonColors.gold_FFCC00 },
  bgColorSilver_C0C0C0: { backgroundColor: commonColors.silver_C0C0C0 },
  bgColorNavy_000080: { backgroundColor: commonColors.navy_000080 },
  bgColorOlive_808000: { backgroundColor: commonColors.olive_808000 },
  bgColorTeal_008080: { backgroundColor: commonColors.teal_008080 },
  bgColorPink_FF69B4: { backgroundColor: commonColors.pink_FF69B4 },
  bgColorLavender_E6E6FA: { backgroundColor: commonColors.lavender_E6E6FA },
  bgColorCoral_FF7F50: { backgroundColor: commonColors.coral_FF7F50 },
  bgColorIndigo_4B0082: { backgroundColor: commonColors.indigo_4B0082 },
  bgColorViolet_EE82EE: { backgroundColor: commonColors.violet_EE82EE },
  bgColorPeach_FFDAB9: { backgroundColor: commonColors.peach_FFDAB9 },
  bgColorMint_98FB98: { backgroundColor: commonColors.mint_98FB98 },
  bgColorSalmon_FA8072: { backgroundColor: commonColors.salmon_FA8072 },
  bgColorBeige_F5F5DC: { backgroundColor: commonColors.beige_F5F5DC },
  bgColorKhaki_F0E68C: { backgroundColor: commonColors.khaki_F0E68C },
  bgColorIvory_FFFFF0: { backgroundColor: commonColors.ivory_FFFFF0 },
  bgColorSienna_A0522D: { backgroundColor: commonColors.sienna_A0522D },
  bgColorAzure_F0FFFF: { backgroundColor: commonColors.azure_F0FFFF },
  bgColorOrchid_DA70D6: { backgroundColor: commonColors.orchid_DA70D6 },
  bgColorChocolate_D2691E: { backgroundColor: commonColors.chocolate_D2691E },
  bgColorTomato_FF6347: { backgroundColor: commonColors.tomato_FF6347 },
  bgColorAqua_00FFFF: { backgroundColor: commonColors.aqua_00FFFF },
  bgColorSkyblue_87CEEB: { backgroundColor: commonColors.skyblue_87CEEB },
  bgColorLinen_FAF0E6: { backgroundColor: commonColors.linen_FAF0E6 },
  bgColorBisque_FFE4C4: { backgroundColor: commonColors.bisque_FFE4C4 },
  bgColorHoneydew_F0FFF0: { backgroundColor: commonColors.honeydew_F0FFF0 },
  bgColorLemonchiffon_FFFACD: {
    backgroundColor: commonColors.lemonchiffon_FFFACD,
  },
  bgColorMistyrose_FFE4E1: { backgroundColor: commonColors.mistyrose_FFE4E1 },
  bgColorMoccasin_FFE4B5: { backgroundColor: commonColors.moccasin_FFE4B5 },
  bgColorNavajowhite_FFDEAD: {
    backgroundColor: commonColors.navajowhite_FFDEAD,
  },
  bgColorOldlace_FDF5E6: { backgroundColor: commonColors.oldlace_FDF5E6 },
  bgColorPapayawhip_FFEFD5: { backgroundColor: commonColors.papayawhip_FFEFD5 },
  bgColorSeashell_FFF5EE: { backgroundColor: commonColors.seashell_FFF5EE },
  bgColorSnow_FFFAFA: { backgroundColor: commonColors.snow_FFFAFA },
  bgColorWhitesmoke_F5F5F5: { backgroundColor: commonColors.whitesmoke_F5F5F5 },
  bgColorYellowgreen_9ACD32: {
    backgroundColor: commonColors.yellowgreen_9ACD32,
  },
  bgColorAntiquewhite_FAEBD7: {
    backgroundColor: commonColors.antiquewhite_FAEBD7,
  },
  bgColorCornflowerblue_6495ED: {
    backgroundColor: commonColors.cornflowerblue_6495ED,
  },
  bgColorDarkblue_00008B: { backgroundColor: commonColors.darkblue_00008B },
  bgColorDarkcyan_008B8B: { backgroundColor: commonColors.darkcyan_008B8B },
  bgColorDarkgoldenrod_B8860B: {
    backgroundColor: commonColors.darkgoldenrod_B8860B,
  },
  bgColorDarkgray_A9A9A9: { backgroundColor: commonColors.darkgray_A9A9A9 },
  bgColorDarkgreen_006400: { backgroundColor: commonColors.darkgreen_006400 },

  //MARK: border width
  borderWidth1: { borderWidth: 1 },
  borderWidth2: { borderWidth: 2 },
  borderWidth3: { borderWidth: 3 },
  borderWidth4: { borderWidth: 4 },
  borderWidth5: { borderWidth: 5 },
  borderWidth6: { borderWidth: 6 },
  borderWidth7: { borderWidth: 7 },
  borderWidth8: { borderWidth: 8 },
  borderWidth9: { borderWidth: 9 },
  borderWidth10: { borderWidth: 10 },

  //MARK: width
  width100: {
    width: '100%',
  },

  //MARK: height
  height100: {
    height: '100%',
  },

  //MARK: margin top
  marginTop1: { marginTop: scale(1) },
  marginTop2: { marginTop: scale(2) },
  marginTop3: { marginTop: scale(3) },
  marginTop4: { marginTop: scale(4) },
  marginTop5: { marginTop: scale(5) },
  marginTop6: { marginTop: scale(6) },
  marginTop7: { marginTop: scale(7) },
  marginTop8: { marginTop: scale(8) },
  marginTop9: { marginTop: scale(9) },
  marginTop10: { marginTop: scale(10) },
  marginTop11: { marginTop: scale(11) },
  marginTop12: { marginTop: scale(12) },
  marginTop13: { marginTop: scale(13) },
  marginTop14: { marginTop: scale(14) },
  marginTop15: { marginTop: scale(15) },
  marginTop16: { marginTop: scale(16) },
  marginTop17: { marginTop: scale(17) },
  marginTop18: { marginTop: scale(18) },
  marginTop19: { marginTop: scale(19) },
  marginTop20: { marginTop: scale(20) },
  marginTop21: { marginTop: scale(21) },
  marginTop22: { marginTop: scale(22) },
  marginTop23: { marginTop: scale(23) },
  marginTop24: { marginTop: scale(24) },
  marginTop25: { marginTop: scale(25) },
  marginTop26: { marginTop: scale(26) },
  marginTop27: { marginTop: scale(27) },
  marginTop28: { marginTop: scale(28) },
  marginTop29: { marginTop: scale(29) },
  marginTop30: { marginTop: scale(30) },
  marginTop31: { marginTop: scale(31) },
  marginTop32: { marginTop: scale(32) },
  marginTop33: { marginTop: scale(33) },
  marginTop34: { marginTop: scale(34) },
  marginTop35: { marginTop: scale(35) },
  marginTop36: { marginTop: scale(36) },
  marginTop37: { marginTop: scale(37) },
  marginTop38: { marginTop: scale(38) },
  marginTop39: { marginTop: scale(39) },
  marginTop40: { marginTop: scale(40) },
  marginTop41: { marginTop: scale(41) },
  marginTop42: { marginTop: scale(42) },
  marginTop43: { marginTop: scale(43) },
  marginTop44: { marginTop: scale(44) },
  marginTop45: { marginTop: scale(45) },
  marginTop46: { marginTop: scale(46) },
  marginTop47: { marginTop: scale(47) },
  marginTop48: { marginTop: scale(48) },
  marginTop49: { marginTop: scale(49) },
  marginTop50: { marginTop: scale(50) },
  marginTop51: { marginTop: scale(51) },
  marginTop52: { marginTop: scale(52) },
  marginTop53: { marginTop: scale(53) },
  marginTop54: { marginTop: scale(54) },
  marginTop55: { marginTop: scale(55) },
  marginTop56: { marginTop: scale(56) },
  marginTop57: { marginTop: scale(57) },
  marginTop58: { marginTop: scale(58) },
  marginTop59: { marginTop: scale(59) },
  marginTop60: { marginTop: scale(60) },
  marginTop61: { marginTop: scale(61) },
  marginTop62: { marginTop: scale(62) },
  marginTop63: { marginTop: scale(63) },
  marginTop64: { marginTop: scale(64) },
  marginTop65: { marginTop: scale(65) },
  marginTop66: { marginTop: scale(66) },
  marginTop67: { marginTop: scale(67) },
  marginTop68: { marginTop: scale(68) },
  marginTop69: { marginTop: scale(69) },
  marginTop70: { marginTop: scale(70) },
  marginTop71: { marginTop: scale(71) },
  marginTop72: { marginTop: scale(72) },
  marginTop73: { marginTop: scale(73) },
  marginTop74: { marginTop: scale(74) },
  marginTop75: { marginTop: scale(75) },
  marginTop76: { marginTop: scale(76) },
  marginTop77: { marginTop: scale(77) },
  marginTop78: { marginTop: scale(78) },
  marginTop79: { marginTop: scale(79) },
  marginTop80: { marginTop: scale(80) },
  marginTop81: { marginTop: scale(81) },
  marginTop82: { marginTop: scale(82) },
  marginTop83: { marginTop: scale(83) },
  marginTop84: { marginTop: scale(84) },
  marginTop85: { marginTop: scale(85) },
  marginTop86: { marginTop: scale(86) },
  marginTop87: { marginTop: scale(87) },
  marginTop88: { marginTop: scale(88) },
  marginTop89: { marginTop: scale(89) },
  marginTop90: { marginTop: scale(90) },
  marginTop91: { marginTop: scale(91) },
  marginTop92: { marginTop: scale(92) },
  marginTop93: { marginTop: scale(93) },
  marginTop94: { marginTop: scale(94) },
  marginTop95: { marginTop: scale(95) },
  marginTop96: { marginTop: scale(96) },
  marginTop97: { marginTop: scale(97) },
  marginTop98: { marginTop: scale(98) },
  marginTop99: { marginTop: scale(99) },
  marginTop100: { marginTop: scale(100) },

  //MARK: margin bottom
  marginBottom1: { marginBottom: scale(1) },
  marginBottom2: { marginBottom: scale(2) },
  marginBottom3: { marginBottom: scale(3) },
  marginBottom4: { marginBottom: scale(4) },
  marginBottom5: { marginBottom: scale(5) },
  marginBottom6: { marginBottom: scale(6) },
  marginBottom7: { marginBottom: scale(7) },
  marginBottom8: { marginBottom: scale(8) },
  marginBottom9: { marginBottom: scale(9) },
  marginBottom10: { marginBottom: scale(10) },
  marginBottom11: { marginBottom: scale(11) },
  marginBottom12: { marginBottom: scale(12) },
  marginBottom13: { marginBottom: scale(13) },
  marginBottom14: { marginBottom: scale(14) },
  marginBottom15: { marginBottom: scale(15) },
  marginBottom16: { marginBottom: scale(16) },
  marginBottom17: { marginBottom: scale(17) },
  marginBottom18: { marginBottom: scale(18) },
  marginBottom19: { marginBottom: scale(19) },
  marginBottom20: { marginBottom: scale(20) },
  marginBottom21: { marginBottom: scale(21) },
  marginBottom22: { marginBottom: scale(22) },
  marginBottom23: { marginBottom: scale(23) },
  marginBottom24: { marginBottom: scale(24) },
  marginBottom25: { marginBottom: scale(25) },
  marginBottom26: { marginBottom: scale(26) },
  marginBottom27: { marginBottom: scale(27) },
  marginBottom28: { marginBottom: scale(28) },
  marginBottom29: { marginBottom: scale(29) },
  marginBottom30: { marginBottom: scale(30) },
  marginBottom31: { marginBottom: scale(31) },
  marginBottom32: { marginBottom: scale(32) },
  marginBottom33: { marginBottom: scale(33) },
  marginBottom34: { marginBottom: scale(34) },
  marginBottom35: { marginBottom: scale(35) },
  marginBottom36: { marginBottom: scale(36) },
  marginBottom37: { marginBottom: scale(37) },
  marginBottom38: { marginBottom: scale(38) },
  marginBottom39: { marginBottom: scale(39) },
  marginBottom40: { marginBottom: scale(40) },
  marginBottom41: { marginBottom: scale(41) },
  marginBottom42: { marginBottom: scale(42) },
  marginBottom43: { marginBottom: scale(43) },
  marginBottom44: { marginBottom: scale(44) },
  marginBottom45: { marginBottom: scale(45) },
  marginBottom46: { marginBottom: scale(46) },
  marginBottom47: { marginBottom: scale(47) },
  marginBottom48: { marginBottom: scale(48) },
  marginBottom49: { marginBottom: scale(49) },
  marginBottom50: { marginBottom: scale(50) },
  marginBottom51: { marginBottom: scale(51) },
  marginBottom52: { marginBottom: scale(52) },
  marginBottom53: { marginBottom: scale(53) },
  marginBottom54: { marginBottom: scale(54) },
  marginBottom55: { marginBottom: scale(55) },
  marginBottom56: { marginBottom: scale(56) },
  marginBottom57: { marginBottom: scale(57) },
  marginBottom58: { marginBottom: scale(58) },
  marginBottom59: { marginBottom: scale(59) },
  marginBottom60: { marginBottom: scale(60) },
  marginBottom61: { marginBottom: scale(61) },
  marginBottom62: { marginBottom: scale(62) },
  marginBottom63: { marginBottom: scale(63) },
  marginBottom64: { marginBottom: scale(64) },
  marginBottom65: { marginBottom: scale(65) },
  marginBottom66: { marginBottom: scale(66) },
  marginBottom67: { marginBottom: scale(67) },
  marginBottom68: { marginBottom: scale(68) },
  marginBottom69: { marginBottom: scale(69) },
  marginBottom70: { marginBottom: scale(70) },
  marginBottom71: { marginBottom: scale(71) },
  marginBottom72: { marginBottom: scale(72) },
  marginBottom73: { marginBottom: scale(73) },
  marginBottom74: { marginBottom: scale(74) },
  marginBottom75: { marginBottom: scale(75) },
  marginBottom76: { marginBottom: scale(76) },
  marginBottom77: { marginBottom: scale(77) },
  marginBottom78: { marginBottom: scale(78) },
  marginBottom79: { marginBottom: scale(79) },
  marginBottom80: { marginBottom: scale(80) },
  marginBottom81: { marginBottom: scale(81) },
  marginBottom82: { marginBottom: scale(82) },
  marginBottom83: { marginBottom: scale(83) },
  marginBottom84: { marginBottom: scale(84) },
  marginBottom85: { marginBottom: scale(85) },
  marginBottom86: { marginBottom: scale(86) },
  marginBottom87: { marginBottom: scale(87) },
  marginBottom88: { marginBottom: scale(88) },
  marginBottom89: { marginBottom: scale(89) },
  marginBottom90: { marginBottom: scale(90) },
  marginBottom91: { marginBottom: scale(91) },
  marginBottom92: { marginBottom: scale(92) },
  marginBottom93: { marginBottom: scale(93) },
  marginBottom94: { marginBottom: scale(94) },
  marginBottom95: { marginBottom: scale(95) },
  marginBottom96: { marginBottom: scale(96) },
  marginBottom97: { marginBottom: scale(97) },
  marginBottom98: { marginBottom: scale(98) },
  marginBottom99: { marginBottom: scale(99) },
  marginBottom100: { marginBottom: scale(100) },

  //MARK: opacity
  opacity1: {
    opacity: 0.1,
  },
  opacity2: {
    opacity: 0.2,
  },
  opacity3: {
    opacity: 0.3,
  },
  opacity4: {
    opacity: 0.4,
  },
  opacity5: {
    opacity: 0.5,
  },
  opacity6: {
    opacity: 0.6,
  },
  opacity7: {
    opacity: 0.7,
  },
  opacity8: {
    opacity: 0.8,
  },
  opacity9: {
    opacity: 0.9,
  },
  opacityOne: {
    opacity: 1,
  },

  //MARK: zIndex
  zIndex1: { zIndex: 1 },
  zIndex2: { zIndex: 2 },
  zIndex3: { zIndex: 3 },
  zIndex4: { zIndex: 4 },
  zIndex5: { zIndex: 5 },
  zIndex6: { zIndex: 6 },
  zIndex7: { zIndex: 7 },
  zIndex8: { zIndex: 8 },
  zIndex9: { zIndex: 9 },
  zIndex10: { zIndex: 10 },

  //MARK: marginRight
  marginRight1: { marginRight: scale(1) },
  marginRight2: { marginRight: scale(2) },
  marginRight3: { marginRight: scale(3) },
  marginRight4: { marginRight: scale(4) },
  marginRight5: { marginRight: scale(5) },
  marginRight6: { marginRight: scale(6) },
  marginRight7: { marginRight: scale(7) },
  marginRight8: { marginRight: scale(8) },
  marginRight9: { marginRight: scale(9) },
  marginRight10: { marginRight: scale(10) },
  marginRight11: { marginRight: scale(11) },
  marginRight12: { marginRight: scale(12) },
  marginRight13: { marginRight: scale(13) },
  marginRight14: { marginRight: scale(14) },
  marginRight15: { marginRight: scale(15) },
  marginRight16: { marginRight: scale(16) },
  marginRight17: { marginRight: scale(17) },
  marginRight18: { marginRight: scale(18) },
  marginRight19: { marginRight: scale(19) },
  marginRight20: { marginRight: scale(20) },
  marginRight21: { marginRight: scale(21) },
  marginRight22: { marginRight: scale(22) },
  marginRight23: { marginRight: scale(23) },
  marginRight24: { marginRight: scale(24) },
  marginRight25: { marginRight: scale(25) },
  marginRight26: { marginRight: scale(26) },
  marginRight27: { marginRight: scale(27) },
  marginRight28: { marginRight: scale(28) },
  marginRight29: { marginRight: scale(29) },
  marginRight30: { marginRight: scale(30) },
  marginRight31: { marginRight: scale(31) },
  marginRight32: { marginRight: scale(32) },
  marginRight33: { marginRight: scale(33) },
  marginRight34: { marginRight: scale(34) },
  marginRight35: { marginRight: scale(35) },
  marginRight36: { marginRight: scale(36) },
  marginRight37: { marginRight: scale(37) },
  marginRight38: { marginRight: scale(38) },
  marginRight39: { marginRight: scale(39) },
  marginRight40: { marginRight: scale(40) },
  marginRight41: { marginRight: scale(41) },
  marginRight42: { marginRight: scale(42) },
  marginRight43: { marginRight: scale(43) },
  marginRight44: { marginRight: scale(44) },
  marginRight45: { marginRight: scale(45) },
  marginRight46: { marginRight: scale(46) },
  marginRight47: { marginRight: scale(47) },
  marginRight48: { marginRight: scale(48) },
  marginRight49: { marginRight: scale(49) },
  marginRight50: { marginRight: scale(50) },
  marginRight51: { marginRight: scale(51) },
  marginRight52: { marginRight: scale(52) },
  marginRight53: { marginRight: scale(53) },
  marginRight54: { marginRight: scale(54) },
  marginRight55: { marginRight: scale(55) },
  marginRight56: { marginRight: scale(56) },
  marginRight57: { marginRight: scale(57) },
  marginRight58: { marginRight: scale(58) },
  marginRight59: { marginRight: scale(59) },
  marginRight60: { marginRight: scale(60) },
  marginRight61: { marginRight: scale(61) },
  marginRight62: { marginRight: scale(62) },
  marginRight63: { marginRight: scale(63) },
  marginRight64: { marginRight: scale(64) },
  marginRight65: { marginRight: scale(65) },
  marginRight66: { marginRight: scale(66) },
  marginRight67: { marginRight: scale(67) },
  marginRight68: { marginRight: scale(68) },
  marginRight69: { marginRight: scale(69) },
  marginRight70: { marginRight: scale(70) },
  marginRight71: { marginRight: scale(71) },
  marginRight72: { marginRight: scale(72) },
  marginRight73: { marginRight: scale(73) },
  marginRight74: { marginRight: scale(74) },
  marginRight75: { marginRight: scale(75) },
  marginRight76: { marginRight: scale(76) },
  marginRight77: { marginRight: scale(77) },
  marginRight78: { marginRight: scale(78) },
  marginRight79: { marginRight: scale(79) },
  marginRight80: { marginRight: scale(80) },
  marginRight81: { marginRight: scale(81) },
  marginRight82: { marginRight: scale(82) },
  marginRight83: { marginRight: scale(83) },
  marginRight84: { marginRight: scale(84) },
  marginRight85: { marginRight: scale(85) },
  marginRight86: { marginRight: scale(86) },
  marginRight87: { marginRight: scale(87) },
  marginRight88: { marginRight: scale(88) },
  marginRight89: { marginRight: scale(89) },
  marginRight90: { marginRight: scale(90) },
  marginRight91: { marginRight: scale(91) },
  marginRight92: { marginRight: scale(92) },
  marginRight93: { marginRight: scale(93) },
  marginRight94: { marginRight: scale(94) },
  marginRight95: { marginRight: scale(95) },
  marginRight96: { marginRight: scale(96) },
  marginRight97: { marginRight: scale(97) },
  marginRight98: { marginRight: scale(98) },
  marginRight99: { marginRight: scale(99) },
  marginRight100: { marginRight: scale(100) },

  //MARK: marginLeft
  marginLeft1: { marginLeft: scale(1) },
  marginLeft2: { marginLeft: scale(2) },
  marginLeft3: { marginLeft: scale(3) },
  marginLeft4: { marginLeft: scale(4) },
  marginLeft5: { marginLeft: scale(5) },
  marginLeft6: { marginLeft: scale(6) },
  marginLeft7: { marginLeft: scale(7) },
  marginLeft8: { marginLeft: scale(8) },
  marginLeft9: { marginLeft: scale(9) },
  marginLeft10: { marginLeft: scale(10) },
  marginLeft11: { marginLeft: scale(11) },
  marginLeft12: { marginLeft: scale(12) },
  marginLeft13: { marginLeft: scale(13) },
  marginLeft14: { marginLeft: scale(14) },
  marginLeft15: { marginLeft: scale(15) },
  marginLeft16: { marginLeft: scale(16) },
  marginLeft17: { marginLeft: scale(17) },
  marginLeft18: { marginLeft: scale(18) },
  marginLeft19: { marginLeft: scale(19) },
  marginLeft20: { marginLeft: scale(20) },
  marginLeft21: { marginLeft: scale(21) },
  marginLeft22: { marginLeft: scale(22) },
  marginLeft23: { marginLeft: scale(23) },
  marginLeft24: { marginLeft: scale(24) },
  marginLeft25: { marginLeft: scale(25) },
  marginLeft26: { marginLeft: scale(26) },
  marginLeft27: { marginLeft: scale(27) },
  marginLeft28: { marginLeft: scale(28) },
  marginLeft29: { marginLeft: scale(29) },
  marginLeft30: { marginLeft: scale(30) },
  marginLeft31: { marginLeft: scale(31) },
  marginLeft32: { marginLeft: scale(32) },
  marginLeft33: { marginLeft: scale(33) },
  marginLeft34: { marginLeft: scale(34) },
  marginLeft35: { marginLeft: scale(35) },
  marginLeft36: { marginLeft: scale(36) },
  marginLeft37: { marginLeft: scale(37) },
  marginLeft38: { marginLeft: scale(38) },
  marginLeft39: { marginLeft: scale(39) },
  marginLeft40: { marginLeft: scale(40) },
  marginLeft41: { marginLeft: scale(41) },
  marginLeft42: { marginLeft: scale(42) },
  marginLeft43: { marginLeft: scale(43) },
  marginLeft44: { marginLeft: scale(44) },
  marginLeft45: { marginLeft: scale(45) },
  marginLeft46: { marginLeft: scale(46) },
  marginLeft47: { marginLeft: scale(47) },
  marginLeft48: { marginLeft: scale(48) },
  marginLeft49: { marginLeft: scale(49) },
  marginLeft50: { marginLeft: scale(50) },
  marginLeft51: { marginLeft: scale(51) },
  marginLeft52: { marginLeft: scale(52) },
  marginLeft53: { marginLeft: scale(53) },
  marginLeft54: { marginLeft: scale(54) },
  marginLeft55: { marginLeft: scale(55) },
  marginLeft56: { marginLeft: scale(56) },
  marginLeft57: { marginLeft: scale(57) },
  marginLeft58: { marginLeft: scale(58) },
  marginLeft59: { marginLeft: scale(59) },
  marginLeft60: { marginLeft: scale(60) },
  marginLeft61: { marginLeft: scale(61) },
  marginLeft62: { marginLeft: scale(62) },
  marginLeft63: { marginLeft: scale(63) },
  marginLeft64: { marginLeft: scale(64) },
  marginLeft65: { marginLeft: scale(65) },
  marginLeft66: { marginLeft: scale(66) },
  marginLeft67: { marginLeft: scale(67) },
  marginLeft68: { marginLeft: scale(68) },
  marginLeft69: { marginLeft: scale(69) },
  marginLeft70: { marginLeft: scale(70) },
  marginLeft71: { marginLeft: scale(71) },
  marginLeft72: { marginLeft: scale(72) },
  marginLeft73: { marginLeft: scale(73) },
  marginLeft74: { marginLeft: scale(74) },
  marginLeft75: { marginLeft: scale(75) },
  marginLeft76: { marginLeft: scale(76) },
  marginLeft77: { marginLeft: scale(77) },
  marginLeft78: { marginLeft: scale(78) },
  marginLeft79: { marginLeft: scale(79) },
  marginLeft80: { marginLeft: scale(80) },
  marginLeft81: { marginLeft: scale(81) },
  marginLeft82: { marginLeft: scale(82) },
  marginLeft83: { marginLeft: scale(83) },
  marginLeft84: { marginLeft: scale(84) },
  marginLeft85: { marginLeft: scale(85) },
  marginLeft86: { marginLeft: scale(86) },
  marginLeft87: { marginLeft: scale(87) },
  marginLeft88: { marginLeft: scale(88) },
  marginLeft89: { marginLeft: scale(89) },
  marginLeft90: { marginLeft: scale(90) },
  marginLeft91: { marginLeft: scale(91) },
  marginLeft92: { marginLeft: scale(92) },
  marginLeft93: { marginLeft: scale(93) },
  marginLeft94: { marginLeft: scale(94) },
  marginLeft95: { marginLeft: scale(95) },
  marginLeft96: { marginLeft: scale(96) },
  marginLeft97: { marginLeft: scale(97) },
  marginLeft98: { marginLeft: scale(98) },
  marginLeft99: { marginLeft: scale(99) },
  marginLeft100: { marginLeft: scale(100) },

  //MARK: borderRadius
  borderRadius1: { borderRadius: scale(1) },
  borderRadius2: { borderRadius: scale(2) },
  borderRadius3: { borderRadius: scale(3) },
  borderRadius4: { borderRadius: scale(4) },
  borderRadius5: { borderRadius: scale(5) },
  borderRadius6: { borderRadius: scale(6) },
  borderRadius7: { borderRadius: scale(7) },
  borderRadius8: { borderRadius: scale(8) },
  borderRadius9: { borderRadius: scale(9) },
  borderRadius10: { borderRadius: scale(10) },
  borderRadius11: { borderRadius: scale(11) },
  borderRadius12: { borderRadius: scale(12) },
  borderRadius13: { borderRadius: scale(13) },
  borderRadius14: { borderRadius: scale(14) },
  borderRadius15: { borderRadius: scale(15) },
  borderRadius16: { borderRadius: scale(16) },
  borderRadius17: { borderRadius: scale(17) },
  borderRadius18: { borderRadius: scale(18) },
  borderRadius19: { borderRadius: scale(19) },
  borderRadius20: { borderRadius: scale(20) },
  borderRadius21: { borderRadius: scale(21) },
  borderRadius22: { borderRadius: scale(22) },
  borderRadius23: { borderRadius: scale(23) },
  borderRadius24: { borderRadius: scale(24) },
  borderRadius25: { borderRadius: scale(25) },
  borderRadius26: { borderRadius: scale(26) },
  borderRadius27: { borderRadius: scale(27) },
  borderRadius28: { borderRadius: scale(28) },
  borderRadius29: { borderRadius: scale(29) },
  borderRadius30: { borderRadius: scale(30) },
  borderRadius31: { borderRadius: scale(31) },
  borderRadius32: { borderRadius: scale(32) },
  borderRadius33: { borderRadius: scale(33) },
  borderRadius34: { borderRadius: scale(34) },
  borderRadius35: { borderRadius: scale(35) },
  borderRadius36: { borderRadius: scale(36) },
  borderRadius37: { borderRadius: scale(37) },
  borderRadius38: { borderRadius: scale(38) },
  borderRadius39: { borderRadius: scale(39) },
  borderRadius40: { borderRadius: scale(40) },
  borderRadius41: { borderRadius: scale(41) },
  borderRadius42: { borderRadius: scale(42) },
  borderRadius43: { borderRadius: scale(43) },
  borderRadius44: { borderRadius: scale(44) },
  borderRadius45: { borderRadius: scale(45) },
  borderRadius46: { borderRadius: scale(46) },
  borderRadius47: { borderRadius: scale(47) },
  borderRadius48: { borderRadius: scale(48) },
  borderRadius49: { borderRadius: scale(49) },
  borderRadius50: { borderRadius: scale(50) },
  borderRadius51: { borderRadius: scale(51) },
  borderRadius52: { borderRadius: scale(52) },
  borderRadius53: { borderRadius: scale(53) },
  borderRadius54: { borderRadius: scale(54) },
  borderRadius55: { borderRadius: scale(55) },
  borderRadius56: { borderRadius: scale(56) },
  borderRadius57: { borderRadius: scale(57) },
  borderRadius58: { borderRadius: scale(58) },
  borderRadius59: { borderRadius: scale(59) },
  borderRadius60: { borderRadius: scale(60) },
  borderRadius61: { borderRadius: scale(61) },
  borderRadius62: { borderRadius: scale(62) },
  borderRadius63: { borderRadius: scale(63) },
  borderRadius64: { borderRadius: scale(64) },
  borderRadius65: { borderRadius: scale(65) },
  borderRadius66: { borderRadius: scale(66) },
  borderRadius67: { borderRadius: scale(67) },
  borderRadius68: { borderRadius: scale(68) },
  borderRadius69: { borderRadius: scale(69) },
  borderRadius70: { borderRadius: scale(70) },
  borderRadius71: { borderRadius: scale(71) },
  borderRadius72: { borderRadius: scale(72) },
  borderRadius73: { borderRadius: scale(73) },
  borderRadius74: { borderRadius: scale(74) },
  borderRadius75: { borderRadius: scale(75) },
  borderRadius76: { borderRadius: scale(76) },
  borderRadius77: { borderRadius: scale(77) },
  borderRadius78: { borderRadius: scale(78) },
  borderRadius79: { borderRadius: scale(79) },
  borderRadius80: { borderRadius: scale(80) },
  borderRadius81: { borderRadius: scale(81) },
  borderRadius82: { borderRadius: scale(82) },
  borderRadius83: { borderRadius: scale(83) },
  borderRadius84: { borderRadius: scale(84) },
  borderRadius85: { borderRadius: scale(85) },
  borderRadius86: { borderRadius: scale(86) },
  borderRadius87: { borderRadius: scale(87) },
  borderRadius88: { borderRadius: scale(88) },
  borderRadius89: { borderRadius: scale(89) },
  borderRadius90: { borderRadius: scale(90) },
  borderRadius91: { borderRadius: scale(91) },
  borderRadius92: { borderRadius: scale(92) },
  borderRadius93: { borderRadius: scale(93) },
  borderRadius94: { borderRadius: scale(94) },
  borderRadius95: { borderRadius: scale(95) },
  borderRadius96: { borderRadius: scale(96) },
  borderRadius97: { borderRadius: scale(97) },
  borderRadius98: { borderRadius: scale(98) },
  borderRadius99: { borderRadius: scale(99) },
  borderRadius100: { borderRadius: scale(100) },
});

export default defaultStyles;
